#!/bin/sh

NAME="tgui"

. ./tmake.sh

tmake_init "$@"

tmake_add_shared_library "libtgui" src/*.c "platform/\$(PLATFORM).c" CFLAGS="-Iinclude -Iinclude/tgui"

tmake_add_executable "tgui-demo" "test/demo.c" CFLAGS="-Iinclude" DEPENDENCIES="libtgui"

tmake_fini
